# Generated by Django 5.1.1 on 2024-10-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_chatsession"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatsession",
            name="user",
        ),
        migrations.AddField(
            model_name="chatsession",
            name="session_identifier",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name="chatsession",
            table="app_chatsessions",
        ),
    ]
