# Generated by Django 5.1.1 on 2024-10-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_chatsession_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="content_map",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="video_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="video_title",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
