# Generated by Django 5.1.1 on 2024-12-25 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_waitlist"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel_name", models.CharField(max_length=255)),
                ("channel_id", models.CharField(max_length=255)),
                ("duration_seconds", models.IntegerField()),
                ("view_count", models.BigIntegerField(blank=True, null=True)),
                ("like_count", models.BigIntegerField(blank=True, null=True)),
                ("published_at", models.DateTimeField()),
                ("captions_type", models.CharField(max_length=50)),
                ("language", models.CharField(default="en", max_length=10)),
                (
                    "thumbnail_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
            ],
            options={
                "db_table": "app_video_metadata",
            },
        ),
        migrations.RemoveField(
            model_name="chatsession",
            name="content_map",
        ),
        migrations.RemoveField(
            model_name="chatsession",
            name="video_id",
        ),
        migrations.RemoveField(
            model_name="chatsession",
            name="video_title",
        ),
        migrations.AddField(
            model_name="chatsession",
            name="processing_time",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="tokens_used",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chat_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="waitlist",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="waitlist",
            name="phone_no",
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resource_id", models.CharField(max_length=255, unique=True)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[("VIDEO", "Video"), ("DOCUMENT", "Document")],
                        default="VIDEO",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("content_map", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "app_resources",
            },
        ),
        migrations.CreateModel(
            name="DocumentMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_type", models.CharField(max_length=50)),
                ("file_size", models.BigIntegerField()),
                ("page_count", models.IntegerField(blank=True, null=True)),
                ("author", models.CharField(blank=True, max_length=255, null=True)),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("last_modified", models.DateTimeField()),
                (
                    "resource",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_metadata",
                        to="app.resource",
                    ),
                ),
            ],
            options={
                "db_table": "app_document_metadata",
            },
        ),
        migrations.AddField(
            model_name="chatsession",
            name="resource",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_sessions",
                to="app.resource",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["session_identifier"], name="app_chatses_session_83ab2a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["created_at"], name="app_chatses_created_ffb762_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["user", "created_at"], name="app_chatses_user_id_eebba6_idx"
            ),
        ),
        migrations.AddField(
            model_name="videometadata",
            name="resource",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video_metadata",
                to="app.resource",
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["resource_type", "resource_id"],
                name="app_resourc_resourc_455073_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["user", "created_at"], name="app_resourc_user_id_a105f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentmetadata",
            index=models.Index(
                fields=["file_type"], name="app_documen_file_ty_144ddf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentmetadata",
            index=models.Index(
                fields=["last_modified"], name="app_documen_last_mo_800ab6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="videometadata",
            index=models.Index(
                fields=["channel_id"], name="app_video_m_channel_31bf29_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="videometadata",
            index=models.Index(
                fields=["published_at"], name="app_video_m_publish_896c61_idx"
            ),
        ),
    ]
