# Generated by Django 5.1.1 on 2024-12-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_chatsession_resource"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="resource_id",
            field=models.CharField(max_length=255),
        ),
    ]
