# Generated by Django 5.1.1 on 2024-12-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_resource_resource_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="resource_id",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
